// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrescriptionApp.Models;

#nullable disable

namespace PrescriptionApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrescriptionApp.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FillStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            Cost = 19.99m,
                            FillStatus = "Filled",
                            MedicationName = "Atorvastatin",
                            RequestTime = new DateTime(2025, 9, 11, 12, 22, 9, 932, DateTimeKind.Local).AddTicks(5728)
                        },
                        new
                        {
                            PrescriptionId = 2,
                            Cost = 12.50m,
                            FillStatus = "Pending",
                            MedicationName = "Lisinopril",
                            RequestTime = new DateTime(2025, 9, 14, 12, 22, 9, 932, DateTimeKind.Local).AddTicks(5902)
                        },
                        new
                        {
                            PrescriptionId = 3,
                            Cost = 8.75m,
                            FillStatus = "New",
                            MedicationName = "Metformin",
                            RequestTime = new DateTime(2025, 9, 15, 12, 22, 9, 932, DateTimeKind.Local).AddTicks(5906)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
